# Generated by Django 3.0 on 2019-12-16 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191216_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='car',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Phone'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='orders',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Orders'),
        ),
    ]
