# Generated by Django 3.0 on 2019-12-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191216_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
