# Generated by Django 3.0 on 2019-12-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_phone_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='nome',
            new_name='name',
        ),
    ]
