# Generated by Django 3.0 on 2019-12-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191217_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='car',
            new_name='cart',
        ),
    ]
