# Generated by Django 3.0 on 2019-12-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191217_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user',
        ),
        migrations.AddField(
            model_name='myuser',
            name='password',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
