# Generated by Django 3.0 on 2019-12-17 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20191217_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='cor',
            new_name='color',
        ),
    ]
