# Generated by Django 3.0 on 2019-12-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_phone_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='img',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
