# Generated by Django 3.0 on 2019-12-17 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20191217_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='img',
        ),
    ]
