# Generated by Django 3.0 on 2019-12-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_phone_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='img',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
